-- 副本组配置：7个副本（4普通+3英雄）
-- Group ID: 50001-50007
-- 全周开放，用每日次数控制
return {
  [50001] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.BLACKROCK_LOWER"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50001,
    ["Stages"] = { 50001, 50002, 50003, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 312,
    ["UI reward2"] = 351,
    ["UI reward3"] = 338,
  },
  [50002] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.STRATHOLME"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50002,
    ["Stages"] = { 50004, 50005, 50006, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 306,
    ["UI reward2"] = 309,
    ["UI reward3"] = 311,
  },
  [50003] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.DIRE_MAUL"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50003,
    ["Stages"] = { 50007, 50008, 50009, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 307,
    ["UI reward2"] = 310,
    ["UI reward3"] = 347,
  },
  [50004] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.SCHNOLOMANCE"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50004,
    ["Stages"] = { 50010, 50011, 50012, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 315,
    ["UI reward2"] = 310,
    ["UI reward3"] = 306,
  },
  [50005] = {
    ["CD"] = 0,
    ["DailyLimit"] = 1,
    ["MaxBuyPerDay"] = 2,
    ["BuyCost"] = 100,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.NAXXRAMAS"),
    ["Difficulty"] = 2,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50005,
    ["Stages"] = { 50013, 50014, 50015, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 405,
    ["UI reward2"] = 406,
    ["UI reward3"] = 409,
  },
  [50006] = {
    ["CD"] = 0,
    ["DailyLimit"] = 1,
    ["MaxBuyPerDay"] = 2,
    ["BuyCost"] = 100,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.BLACKWING_LAIR"),
    ["Difficulty"] = 2,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50006,
    ["Stages"] = { 50016, 50017, 50018, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 417,
    ["UI reward2"] = 419,
    ["UI reward3"] = 412,
  },
  [50007] = {
    ["CD"] = 0,
    ["DailyLimit"] = 1,
    ["MaxBuyPerDay"] = 2,
    ["BuyCost"] = 100,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.RUINS_OF_AHN_QIRAJ"),
    ["Difficulty"] = 2,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 50007,
    ["Stages"] = { 50019, 50020, 50021, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 413,
    ["UI reward2"] = 414,
    ["UI reward3"] = 416,
  },
}
