-- 副本组配置：7个副本（4普通+3英雄）
-- Group ID: 40001-40007
-- 全周开放，用每日次数控制
return {
  [40001] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.BLACKROCK_LOWER"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40001,
    ["Stages"] = { 40001, 40002, 40003, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 312,
    ["UI reward2"] = 351,
    ["UI reward3"] = 338,
  },
  [40002] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.STRATHOLME"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40002,
    ["Stages"] = { 40004, 40005, 40006, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 306,
    ["UI reward2"] = 309,
    ["UI reward3"] = 311,
  },
  [40003] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.DIRE_MAUL"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40003,
    ["Stages"] = { 40007, 40008, 40009, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 307,
    ["UI reward2"] = 310,
    ["UI reward3"] = 347,
  },
  [40004] = {
    ["CD"] = 0,
    ["DailyLimit"] = 2,
    ["MaxBuyPerDay"] = 3,
    ["BuyCost"] = 50,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.SCHNOLOMANCE"),
    ["Difficulty"] = 1,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40004,
    ["Stages"] = { 40010, 40011, 40012, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 315,
    ["UI reward2"] = 310,
    ["UI reward3"] = 306,
  },
  [40005] = {
    ["CD"] = 0,
    ["DailyLimit"] = 1,
    ["MaxBuyPerDay"] = 2,
    ["BuyCost"] = 100,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.NAXXRAMAS"),
    ["Difficulty"] = 2,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40005,
    ["Stages"] = { 40013, 40014, 40015, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 405,
    ["UI reward2"] = 406,
    ["UI reward3"] = 409,
  },
  [40006] = {
    ["CD"] = 0,
    ["DailyLimit"] = 1,
    ["MaxBuyPerDay"] = 2,
    ["BuyCost"] = 100,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.BLACKWING_LAIR"),
    ["Difficulty"] = 2,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40006,
    ["Stages"] = { 40016, 40017, 40018, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 417,
    ["UI reward2"] = 419,
    ["UI reward3"] = 412,
  },
  [40007] = {
    ["CD"] = 0,
    ["DailyLimit"] = 1,
    ["MaxBuyPerDay"] = 2,
    ["BuyCost"] = 100,
    ["Currency"] = "dungeonpoint",
    ["Group Name"] = LSTR("DUNGEON.RUINS_OF_AHN_QIRAJ"),
    ["Difficulty"] = 2,
    ["Monday"] = true, ["Tuesday"] = true, ["Wednesday"] = true,
    ["Thursday"] = true, ["Friday"] = true, ["Saturday"] = true, ["Sunday"] = true,
    ["Stage Group"] = 40007,
    ["Stages"] = { 40019, 40020, 40021, 0, 0, 0, 0, 0 },
    ["UI reward1"] = 413,
    ["UI reward2"] = 414,
    ["UI reward3"] = 416,
  },
}
