return {
  [40001] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 80,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 312,
    ["Raid Bonus ID 2"] = 351,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40001,
    ["Stage ID"] = 40001,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_LAVA_BEAST"),
    ["UI reward1"] = 312, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 351, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40002] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 82,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 352,
    ["Raid Bonus ID 2"] = 305,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40001,
    ["Stage ID"] = 40002,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_FIRE_CRAFTER"),
    ["UI reward1"] = 352, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 305, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40003] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 300,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 85,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 318,
    ["Raid Bonus ID 2"] = 308,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40001,
    ["Stage ID"] = 40003,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_DARK_IRON_LORD"),
    ["UI reward1"] = 318, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 308, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40004] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 80,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 306,
    ["Raid Bonus ID 2"] = 309,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40002,
    ["Stage ID"] = 40004,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_PLAGUE_BRINGER"),
    ["UI reward1"] = 306, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 309, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40005] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 82,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 311,
    ["Raid Bonus ID 2"] = 345,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40002,
    ["Stage ID"] = 40005,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_FLESH_ABOMINATION"),
    ["UI reward1"] = 311, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 345, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40006] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 300,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 85,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 348,
    ["Raid Bonus ID 2"] = 315,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40002,
    ["Stage ID"] = 40006,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_DEATH_KNIGHT"),
    ["UI reward1"] = 348, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 315, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40007] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 82,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 307,
    ["Raid Bonus ID 2"] = 319,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40003,
    ["Stage ID"] = 40007,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_TWISTED_TREANT"),
    ["UI reward1"] = 307, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 319, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40008] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 84,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 310,
    ["Raid Bonus ID 2"] = 346,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40003,
    ["Stage ID"] = 40008,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_DEMON_GUARD"),
    ["UI reward1"] = 310, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 346, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40009] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 300,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 87,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 347,
    ["Raid Bonus ID 2"] = 349,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40003,
    ["Stage ID"] = 40009,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_PRINCE_OF_DOOM"),
    ["UI reward1"] = 347, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 349, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40010] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 280,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 85,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 315,
    ["Raid Bonus ID 2"] = 345,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40004,
    ["Stage ID"] = 40010,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_FROST_LECTURER"),
    ["UI reward1"] = 315, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 345, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40011] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 280,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 86,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 310,
    ["Raid Bonus ID 2"] = 319,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40004,
    ["Stage ID"] = 40011,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_SHADOW_STUDENT"),
    ["UI reward1"] = 310, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 319, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40012] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 320,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 88,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 306,
    ["Raid Bonus ID 2"] = 311,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40004,
    ["Stage ID"] = 40012,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_HEADMASTER_GADING"),
    ["UI reward1"] = 306, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 311, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 1,
  },
  [40013] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 500,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 90,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 405,
    ["Raid Bonus ID 2"] = 407,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40005,
    ["Stage ID"] = 40013,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_INSTRUCTOR_RAZUVIUS"),
    ["UI reward1"] = 405, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 407, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40014] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 500,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 92,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 406,
    ["Raid Bonus ID 2"] = 408,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40005,
    ["Stage ID"] = 40014,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_PLAGUE_NORTH"),
    ["UI reward1"] = 406, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 408, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40015] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 18,
    ["Fail Exp Reward"] = 9,
    ["Heroexp Reward"] = 600,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 95,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 409,
    ["Raid Bonus ID 2"] = 420,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40005,
    ["Stage ID"] = 40015,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_KELTHUZAD"),
    ["UI reward1"] = 409, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 420, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40016] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 550,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 93,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 417,
    ["Raid Bonus ID 2"] = 418,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40006,
    ["Stage ID"] = 40016,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_RAZORGORE"),
    ["UI reward1"] = 417, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 418, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40017] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 550,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 96,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 419,
    ["Raid Bonus ID 2"] = 411,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40006,
    ["Stage ID"] = 40017,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_VAELASTRAZ"),
    ["UI reward1"] = 419, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 411, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40018] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 18,
    ["Fail Exp Reward"] = 9,
    ["Heroexp Reward"] = 650,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 99,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 412,
    ["Raid Bonus ID 2"] = 410,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40006,
    ["Stage ID"] = 40018,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_NEFARIAN"),
    ["UI reward1"] = 412, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 410, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40019] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 600,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 95,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 413,
    ["Raid Bonus ID 2"] = 421,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40007,
    ["Stage ID"] = 40019,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_SKERAM"),
    ["UI reward1"] = 413, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 421, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40020] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 600,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 98,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 414,
    ["Raid Bonus ID 2"] = 415,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40007,
    ["Stage ID"] = 40020,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_SARTURA"),
    ["UI reward1"] = 414, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 415, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
  [40021] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 2,
    ["Exp Reward"] = 20,
    ["Fail Exp Reward"] = 10,
    ["Heroexp Reward"] = 700,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 100,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 416,
    ["Raid Bonus ID 2"] = 422,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 40007,
    ["Stage ID"] = 40021,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_CTHUN"),
    ["UI reward1"] = 416, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 422, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 1,
  },
}
