local data = {
  [50001] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 80,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 312,
    ["Raid Bonus ID 2"] = 351,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50001,
    ["Stage ID"] = 50001,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_LAVA_BEAST"),
    ["description"] = LSTR("DUNGEON.DESC_LAVA_BEAST"),
    ["UI reward1"] = 312, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 351, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50002] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 82,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 352,
    ["Raid Bonus ID 2"] = 305,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50001,
    ["Stage ID"] = 50002,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_FIRE_CRAFTER"),
    ["description"] = LSTR("DUNGEON.DESC_FIRE_CRAFTER"),
    ["UI reward1"] = 352, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 305, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50003] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 300,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 85,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 318,
    ["Raid Bonus ID 2"] = 308,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50001,
    ["Stage ID"] = 50003,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_DARK_IRON_LORD"),
    ["description"] = LSTR("DUNGEON.DESC_DARK_IRON_LORD"),
    ["UI reward1"] = 318, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 308, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50004] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 80,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 306,
    ["Raid Bonus ID 2"] = 309,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50002,
    ["Stage ID"] = 50004,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_PLAGUE_BRINGER"),
    ["description"] = LSTR("DUNGEON.DESC_PLAGUE_BRINGER"),
    ["UI reward1"] = 306, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 309, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50005] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 82,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 311,
    ["Raid Bonus ID 2"] = 345,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50002,
    ["Stage ID"] = 50005,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_FLESH_ABOMINATION"),
    ["description"] = LSTR("DUNGEON.DESC_FLESH_ABOMINATION"),
    ["UI reward1"] = 311, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 345, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50006] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 300,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 85,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 348,
    ["Raid Bonus ID 2"] = 315,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50002,
    ["Stage ID"] = 50006,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_DEATH_KNIGHT"),
    ["description"] = LSTR("DUNGEON.DESC_DEATH_KNIGHT"),
    ["UI reward1"] = 348, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 315, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50007] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 82,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 307,
    ["Raid Bonus ID 2"] = 319,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50003,
    ["Stage ID"] = 50007,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_TWISTED_TREANT"),
    ["description"] = LSTR("DUNGEON.DESC_TWISTED_TREANT"),
    ["UI reward1"] = 307, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 319, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50008] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 250,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 84,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 310,
    ["Raid Bonus ID 2"] = 346,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50003,
    ["Stage ID"] = 50008,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_DEMON_GUARD"),
    ["description"] = LSTR("DUNGEON.DESC_DEMON_GUARD"),
    ["UI reward1"] = 310, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 346, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50009] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 300,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 87,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 347,
    ["Raid Bonus ID 2"] = 349,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50003,
    ["Stage ID"] = 50009,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_PRINCE_OF_DOOM"),
    ["description"] = LSTR("DUNGEON.DESC_PRINCE_OF_DOOM"),
    ["UI reward1"] = 347, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 349, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50010] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 280,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 85,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 315,
    ["Raid Bonus ID 2"] = 345,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50004,
    ["Stage ID"] = 50010,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_FROST_LECTURER"),
    ["description"] = LSTR("DUNGEON.DESC_FROST_LECTURER"),
    ["UI reward1"] = 315, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 345, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50011] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 10,
    ["Fail Exp Reward"] = 5,
    ["Heroexp Reward"] = 280,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 86,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 310,
    ["Raid Bonus ID 2"] = 319,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50004,
    ["Stage ID"] = 50011,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_SHADOW_STUDENT"),
    ["description"] = LSTR("DUNGEON.DESC_SHADOW_STUDENT"),
    ["UI reward1"] = 310, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 319, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50012] = {
    ["Chapter ID"] = 201,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 12,
    ["Fail Exp Reward"] = 6,
    ["Heroexp Reward"] = 320,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 88,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 306,
    ["Raid Bonus ID 2"] = 311,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50004,
    ["Stage ID"] = 50012,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_HEADMASTER_GADING"),
    ["description"] = LSTR("DUNGEON.DESC_HEADMASTER_GADING"),
    ["UI reward1"] = 306, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 311, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 60,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 12,
    ["Waves"] = 3,
  },
  [50013] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 500,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 90,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 405,
    ["Raid Bonus ID 2"] = 407,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50005,
    ["Stage ID"] = 50013,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_INSTRUCTOR_RAZUVIUS"),
    ["description"] = LSTR("DUNGEON.DESC_INSTRUCTOR_RAZUVIUS"),
    ["UI reward1"] = 405, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 407, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50014] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 500,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 92,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 406,
    ["Raid Bonus ID 2"] = 408,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50005,
    ["Stage ID"] = 50014,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_PLAGUE_NORTH"),
    ["description"] = LSTR("DUNGEON.DESC_PLAGUE_NORTH"),
    ["UI reward1"] = 406, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 408, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50015] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 18,
    ["Fail Exp Reward"] = 9,
    ["Heroexp Reward"] = 600,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 95,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 409,
    ["Raid Bonus ID 2"] = 420,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50005,
    ["Stage ID"] = 50015,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_KELTHUZAD"),
    ["description"] = LSTR("DUNGEON.DESC_KELTHUZAD"),
    ["UI reward1"] = 409, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 420, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50016] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 550,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 93,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 417,
    ["Raid Bonus ID 2"] = 418,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50006,
    ["Stage ID"] = 50016,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_RAZORGORE"),
    ["description"] = LSTR("DUNGEON.DESC_RAZORGORE"),
    ["UI reward1"] = 417, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 418, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50017] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 550,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 96,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 419,
    ["Raid Bonus ID 2"] = 411,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50006,
    ["Stage ID"] = 50017,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_VAELASTRAZ"),
    ["description"] = LSTR("DUNGEON.DESC_VAELASTRAZ"),
    ["UI reward1"] = 419, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 411, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50018] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 18,
    ["Fail Exp Reward"] = 9,
    ["Heroexp Reward"] = 650,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 99,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 412,
    ["Raid Bonus ID 2"] = 410,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50006,
    ["Stage ID"] = 50018,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_NEFARIAN"),
    ["description"] = LSTR("DUNGEON.DESC_NEFARIAN"),
    ["UI reward1"] = 412, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 410, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50019] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 600,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 95,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 413,
    ["Raid Bonus ID 2"] = 421,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50007,
    ["Stage ID"] = 50019,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_SKERAM"),
    ["description"] = LSTR("DUNGEON.DESC_SKERAM"),
    ["UI reward1"] = 413, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 421, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50020] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 15,
    ["Fail Exp Reward"] = 7,
    ["Heroexp Reward"] = 600,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 98,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 414,
    ["Raid Bonus ID 2"] = 415,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50007,
    ["Stage ID"] = 50020,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_SARTURA"),
    ["description"] = LSTR("DUNGEON.DESC_SARTURA"),
    ["UI reward1"] = 414, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 415, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
  [50021] = {
    ["Chapter ID"] = 202,
    ["Chest For FD"] = false,
    ["Daily Limit"] = 0,
    ["Difficulty"] = 1,
    ["Exp Reward"] = 20,
    ["Fail Exp Reward"] = 10,
    ["Heroexp Reward"] = 700,
    ["Key Stage"] = false,
    ["Loot 1 Name"] = 0, ["Loot 2 Name"] = 0, ["Loot 3 Name"] = 0,
    ["Loot 4 Name"] = 0, ["Loot 5 Name"] = 0, ["Loot 6 Name"] = 0, ["Loot 7 Name"] = 0,
    ["Monster Level"] = 100,
    ["Raid Bonus Amount 1"] = 1, ["Raid Bonus Amount 2"] = 1,
    ["Raid Bonus Amount 3"] = 0, ["Raid Bonus Amount 4"] = 0,
    ["Raid Bonus ID 1"] = 416,
    ["Raid Bonus ID 2"] = 422,
    ["Raid Bonus ID 3"] = 0, ["Raid Bonus ID 4"] = 0,
    ["Raid Bonus Type 1"] = "Equip", ["Raid Bonus Type 2"] = "Equip",
    ["Raid Bonus Type 3"] = "Item",
    ["Require Stage"] = 0, ["Require Stars"] = 0,
    ["Stage Group"] = 50007,
    ["Stage ID"] = 50021,
    ["Stage Name"] = LSTR("DUNGEON.BOSS_CTHUN"),
    ["description"] = LSTR("DUNGEON.DESC_CTHUN"),
    ["UI reward1"] = 416, ["UI reward1 Max Amount"] = 1, ["UI reward1 Min Amount"] = 0,
    ["UI reward2"] = 422, ["UI reward2 Max Amount"] = 1, ["UI reward2 Min Amount"] = 0,
    ["UI reward3"] = 0, ["UI reward3 Max Amount"] = 0, ["UI reward3 Min Amount"] = 0,
    ["UI reward4"] = 0, ["UI reward4 Max Amount"] = 0, ["UI reward4 Min Amount"] = 0,
    ["UI reward5"] = 0, ["UI reward5 Max Amount"] = 0, ["UI reward5 Min Amount"] = 0,
    ["UI reward6"] = 0, ["UI reward6 Max Amount"] = 0, ["UI reward6 Min Amount"] = 0,
    ["UI reward7"] = 0, ["UI reward7 Max Amount"] = 0, ["UI reward7 Min Amount"] = 0,
    ["Unlock Level"] = 80,
    ["Vit Return"] = 0,
    ["Vitality Cost"] = 18,
    ["Waves"] = 3,
  },
}

-- 运行时生成难度变体：精英(Diff=2, +1000), 英雄(Diff=3, +2000), 噩梦(Diff=4, +3000)
local diffConfig = {
  [2] = { vitAdd = 4,  mlAdd = 5,  ulAdd = 5,  expAdd = 3,  heroMul = 1.2, keyCost = 0 },
  [3] = { vitAdd = 8,  mlAdd = 10, ulAdd = 10, expAdd = 6,  heroMul = 1.4, keyCost = 1 },
  [4] = { vitAdd = 12, mlAdd = 15, ulAdd = 20, expAdd = 10, heroMul = 1.8, keyCost = 2 },
}

for baseId = 50001, 50021 do
  local base = data[baseId]
  if base then
    for diff = 2, 4 do
      local cfg = diffConfig[diff]
      local newId = baseId + (diff - 1) * 1000
      local entry = {}
      entry["Chapter ID"] = base["Chapter ID"]
      entry["Chest For FD"] = false
      entry["Daily Limit"] = 0
      entry["Difficulty"] = diff
      entry["Exp Reward"] = base["Exp Reward"] + cfg.expAdd
      entry["Fail Exp Reward"] = base["Fail Exp Reward"] + math.floor(cfg.expAdd / 3)
      entry["Heroexp Reward"] = math.floor(base["Heroexp Reward"] * cfg.heroMul)
      entry["Key Cost"] = cfg.keyCost
      entry["Key Stage"] = false
      for i = 1, 7 do entry["Loot " .. i .. " Name"] = 0 end
      entry["Monster Level"] = base["Monster Level"] + cfg.mlAdd
      entry["Raid Bonus Amount 1"] = base["Raid Bonus Amount 1"]
      entry["Raid Bonus Amount 2"] = base["Raid Bonus Amount 2"]
      entry["Raid Bonus Amount 3"] = 0
      entry["Raid Bonus Amount 4"] = 0
      entry["Raid Bonus ID 1"] = base["Raid Bonus ID 1"]
      entry["Raid Bonus ID 2"] = base["Raid Bonus ID 2"]
      entry["Raid Bonus ID 3"] = 0
      entry["Raid Bonus ID 4"] = 0
      entry["Raid Bonus Type 1"] = base["Raid Bonus Type 1"]
      entry["Raid Bonus Type 2"] = base["Raid Bonus Type 2"]
      entry["Raid Bonus Type 3"] = "Item"
      entry["Require Stage"] = 0
      entry["Require Stars"] = 0
      entry["Stage Group"] = base["Stage Group"]
      entry["Stage ID"] = newId
      entry["Stage Name"] = base["Stage Name"]
      entry["UI reward1"] = base["UI reward1"]
      entry["UI reward1 Max Amount"] = base["UI reward1 Max Amount"]
      entry["UI reward1 Min Amount"] = base["UI reward1 Min Amount"]
      entry["UI reward2"] = base["UI reward2"]
      entry["UI reward2 Max Amount"] = base["UI reward2 Max Amount"]
      entry["UI reward2 Min Amount"] = base["UI reward2 Min Amount"]
      for i = 3, 7 do
        entry["UI reward" .. i] = 0
        entry["UI reward" .. i .. " Max Amount"] = 0
        entry["UI reward" .. i .. " Min Amount"] = 0
      end
      entry["Unlock Level"] = base["Unlock Level"] + cfg.ulAdd
      entry["Vit Return"] = 0
      entry["Vitality Cost"] = base["Vitality Cost"] + cfg.vitAdd
      entry["Waves"] = 1
      data[newId] = entry
    end
  end
end

return data
